version: '3'
services:
  node:
    build:
      context: node
    container_name: node
    tty: true
    entrypoint: sh -c "npm install && npm start"
    volumes:
      - ./node:/usr/src/app 
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - node
  
  database:
    image: mysql:5.7
    container_name: database
    ports:
      - "3306:3306"
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - mysql:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 20s
      retries: 5

volumes:
  mysql:
    driver: local
